name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          extensions: opentelemetry, redis
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
          working-directory: ./src

      - name: Validate Symfony configuration
        run: |
          cd src
          php bin/console lint:yaml config/
          php bin/console cache:clear


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build
          docker tag app yeklalex/isrpo-expense-tracker-itmo:latest
          docker push yeklalex/isrpo-expense-tracker-itmo:latest